### ISSUE TITLE
Unable to bulk update podcasts through the web interface andd through the CLI interface

### ISSUE THREAD

**Issue by bmp** [YunoHost-Apps/ampache_ynh#124]
### Describe the bug

The podcasts which are in a catalog of their own fail to update both through the web interface and through the command-line for Ampache. However, "sync"ing each podcast individually through the web interface seems to work.

### Context

- Hardware: Raspberry Pi 4B at home
- YunoHost version: 11.2.7 (stable).
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
  - If yes, please explain:
- Using, or trying to install package version/branch: 6.1.0~ynh1

### Steps to reproduce

1. When I click the Update catalog button in the web interface, I get the message "Catalog update process has started" and even after a substantial time (the update isn't reflected). I have set up the, `# episodes to download when new episodes are available` to 3 and `# latest episodes to keep` to 10.

2. In order to check what was happening, I checked the guide available at [Ampache Github](https://github.com/ampache/ampache/wiki/Podcasts) , and ran `sudo -u www-data php /var/www/ampache/bin/cli run:updateCatalog Podcasts -a` as suggested in the guide, I get the message that the user isn't authorized to do so. When I run this command as root, the error I get is,

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.2.0". You are running 7.4.33.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 7.4.33. in /var/www/ampache/vendor/composer/platform_check.php on line 24

### Expected behavior

The catalog is updated by Ampache.

### Logs

There are no relevant logs to be added.

**Comment by bmp** [comment]
When I force the update using php8.2 with `sudo -u www-data php8.2 /var/www/ampache/bin/cli run:updateCatalog Podcasts -a`, I get the following error,
```
PHP Warning:  parse_ini_file(/var/www/ampache/config/ampache.cfg.php): Failed to open stream: Permission denied in /var/www/ampache/src/Config/Init/InitializationHandlerConfig.php on line 59
PHP Fatal error:  Uncaught Ampache\Config\Init\Exception\ConfigFileNotParsableException: Config file read error in /var/www/ampache/src/Config/Init/InitializationHandlerConfig.php:62
Stack trace:
#0 /var/www/ampache/src/Config/Init/Init.php(61): Ampache\Config\Init\InitializationHandlerConfig->init()
#1 /var/www/ampache/src/Config/Init.php(38): Ampache\Config\Init\Init->init()
#2 /var/www/ampache/bin/cli(37): require('...')
#3 {main}
  thrown in /var/www/ampache/src/Config/Init/InitializationHandlerConfig.php on line 62
```
